# for local execution
  
services:
  redmine:
    depends_on:
      redmine-memcached:
        condition: service_started
      redmine-mysql:
        condition: service_healthy
    build: ./docker/redmine-plugin-dev
    image: redmine-plugin-dev
    init: true
    command: [
      "rails", "s",
      "-e", "production",
      "-b", "0.0.0.0",
    ]
    ports:
     - "3000:3000"
    volumes:
    - ./runtime/redmine/usr/src/redmine/config:/usr/src/redmine/config
    - ./runtime/redmine/usr/src/redmine/files:/usr/src/redmine/files
    - ./runtime/redmine/usr/src/redmine/log:/usr/src/redmine/log
    - ./runtime/redmine/usr/src/redmine/plugins:/usr/src/redmine/plugins
    - ./runtime/redmine/usr/src/redmine/tmp:/usr/src/redmine/tmp
    - ./runtime/redmine/usr/src/redmine/vendor:/usr/src/redmine/vendor
  redmine-mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_DATABASE=redmine
      # specify in .env
      - MYSQL_ROOT_PASSWORD
    volumes:
    - ./runtime/mysql/var/lib/mysql/:/var/lib/mysql/
    - ./runtime/mysql/var/log/mysql/:/var/log/mysql/
    - ./runtime/mysql/etc/mysql/conf.d/:/etc/mysql/conf.d/
    - ./backup/:/backup/
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 10s

  redmine-memcached:
    image: memcached
    restart: on-failure
