# for local execution
  
version: '3.7'

services:
  redmine:
    depends_on:
    - redmine-memcached
    - redmine-mysql
    build: ./docker/redmine-plugin-dev
    image: redmine-plugin-dev
    init: true
    command: [
      "rails", "s",
      "-e", "production",
      "-b", "0.0.0.0",
    ]
    ports:
     - "3000:3000"
    volumes:
    - ./runtime/usr/src/redmine/app/assets:/usr/src/redmine/app/assets
    - ./runtime/usr/src/redmine/config:/usr/src/redmine/config
    - ./runtime/usr/src/redmine/files:/usr/src/redmine/files
    - ./runtime/usr/src/redmine/log:/usr/src/redmine/log
    - ./runtime/usr/src/redmine/plugins:/usr/src/redmine/plugins
    - ./runtime/usr/src/redmine/tmp:/usr/src/redmine/tmp
    - ./runtime/usr/src/redmine/vendor:/usr/src/redmine/vendor
  redmine-mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_DATABASE=redmine
      # specify in .env
      - MYSQL_ROOT_PASSWORD
    volumes:
    - ./runtime/mysql/var/lib/mysql/:/var/lib/mysql/
    - ./runtime/mysql/var/log/mysql/:/var/log/mysql/
    - ./runtime/mysql/etc/mysql/conf.d/:/etc/mysql/conf.d/
    - ./backup/:/backup/
  redmine-memcached:
    image: memcached

